# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: vg2222.DesktopTools
PackageVersion: 1.2.7
InstallerLocale: en-US
MinimumOSVersion: 10.0.22000.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: DesktopTools-win-x64\DesktopTools.exe
  PortableCommandAlias: desktoptools
Commands:
- desktoptools
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/vg2222/DesktopTools/releases/download/v1.2.7/DesktopTools-1.2.7-win-x64-portable.zip
  InstallerSha256: 277E9609D8764F8E5A5A330EFC98F376432427AD2C25BF430361C01D4A4B24F1
ManifestType: installer
ManifestVersion: 1.6.0
